### PR TITLE
Show all pages

### PR DESCRIPTION
**Pull request by mbavio**
This adds support for rendering all pages at once by using a new attribute: `show-all-pages`

### CODE REVIEW

**Comment by winkerVSbecks** [comment]
sorry I'm no longer maintaining this

**Comment by mbavio** [comment]
@winkerVSbecks Care to transfer the project, mate?

**Comment by winkerVSbecks** [comment]
@mbavio sure

**Comment by winkerVSbecks** [comment]
@mbavio won't let me do it since you already have a fork. Can you rename your fork?

**Comment by mbavio** [comment]
Done!


On June 6, 2016 at 8:52:24 PM, Varun Vachhar (notifications@github.com)
wrote:

@mbavio <https://github.com/mbavio> won't let me do it since you already
have a fork. Can you rename your fork?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/winkerVSbecks/angular-pdf-viewer/pull/51#issuecomment-224123210>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAAWIO9Y69Jsmx9UtzsVcuT_05DvBnCAks5qJLK1gaJpZM4Hjcry>
.

**Comment by winkerVSbecks** [comment]
Still can't do it. Apparently: 

> The target account must not have a repository with the same name, or a fork in the same network.

You probably have to delete your fork. If you submit a PR of your fork I can merge it to the https://github.com/winkerVSbecks/angular-pdf-viewer/tree/mbavio branch and then you can take over from there once you get the ownership – merging to `master`, etc.

**Comment by mbavio** [comment]
Never mind, I can keep development on my own fork, don’t worry about it.


On June 6, 2016 at 8:58:01 PM, Varun Vachhar (notifications@github.com)
wrote:

Still can't do it. Apparently:

The target account must not have a repository with the same name, or a fork
in the same network.

You probably have to delete your fork. If you submit a PR of your fork I
can merge it to the
https://github.com/winkerVSbecks/angular-pdf-viewer/tree/mbavio branch and
then you can take over from there once you get the ownership – merging to
master, etc.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/winkerVSbecks/angular-pdf-viewer/pull/51#issuecomment-224124126>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAAWIN4LGcjQss65tEngMGFj2DCI3q88ks5qJLQJgaJpZM4Hjcry>
.

**Comment by winkerVSbecks** [comment]
I added you as a collaborator at least.

**Comment by mbavio** [comment]
That also works, thanks!

**Pull request closed without merging**
